# 1. Jupyter Notebook

To run this notebook locally with Jupyter, activate the virtual environment and run command <mark style=background-color:grey>pip install notebook</mark> . Then <mark style=background-color:grey>cd</mark>  to a directory and run command <mark style=background-color:grey>jupyter notebook</mark>. You'll see a screen show all available notebooks in the directory. Click <mark style=background-color:grey>Python Tutorial.ipynb</mark> and follow the instructions in the notebook.

# 2. Python Syntax

## 2.1 Data types

In [ ]:
# Numbers: Integers and floats

x = 3
y = 2.5

# data type
print(type(x)) # Prints "<class 'int'>"
print(type(y)) # Prints "<class 'float'>"

# Mathematic operations
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25" , won't change value of y

#Mathematic operations
# Addition; prints "4"
print(x + 1)   
x += 1; print(x)  # Change the value of x

# Subtraction; prints "3"
print(x - 1)
x -= 1; print(x) # Change the value of x

# Multiplication; prints "6"
print(x * 2)
x *= 2; print(x) # Change the value of x

# Exponentiation; prints "36"
print(x ** 2)  

#Unlike other languagues, there is no operator like x++ or x-- in python

In [ ]:
# Booleans
# Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (&&, ||, etc.):

t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"


In [ ]:
# Strings

hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.

''
# String length; prints "5"
print(len(hello))  

# String concatenation
hw = hello + ' ' + world  
print(hw)  # prints "hello world"

hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(hw12)  # prints "hello world 12"

# Some other useful methods
print(hello.capitalize())  # Capitalize a string; prints "Hello"
print(hello.upper())       # Convert a string to uppercase; prints "HELLO"
print(hello.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(hello.center(7))     # Center a string, padding with spaces; prints " hello "
print(hello.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

## 2.2 Containers

In [ ]:
# Lists

# Create a list
example_list = [1, 2, 'three', [4, 5, 6]] # Lists can contain elements of different types


# Indexing
print(example_list[3][1])   # prints "5"
print(example_list[-1])     # Negative indices count from the end of the list; prints "[4,5,6]"
example_list.append('four') # Add a new element to the end of the list
print(example_list)         # prints "[1, 2, 'three', [4, 5, 6], 'four']"
example_list.pop()          # Remove and return the last element of the list
print(example_list)         # prints "[1, 2, 'three', [4, 5, 6]]"

# Slicing
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # prints "[0, 1, 8, 9, 4]"


# Sorting
rand_list = [3, 12, 5, 6]
sorted_list = sorted(rand_list)                            # Sort a list
print(sorted_list)                                         # prints "[3, 5, 6, 12]"
rand_list2 = [(3, 'A'), (12, 'D'), (5, 'K'), (6, 'C')]     # Given additional key parameter, and sorted on the given key
sorted_list2 = sorted(rand_list2, key = lambda x: x[1])   # prints "[(3, 'A'), (6, 'C'), (12, 'D'), (5, 'K')]"
print(sorted_list2)

# Loops
nums = list(range(5))
for num in nums:
    print(num)                         # prints "0", "1", "2", "3", "4", each on its own line.
for idx, num in enumerate(nums):
    print('#%d: %s' % (idx + 1, num))  # prints "#1: 0", "#2: 1", "#3: 2", "#4: 3", "#5: 4", each on its own line

# List comprehensions
number = [x for x in nums]
print(number)                              # prints "0, 1, 2 , 3, 4", on one line


squares = []
for x in nums:
    squares.append(x ** 2)                            # Get the square of each component in the list
print(squares)                                        # prints [0, 1, 4, 9, 16]

squares = [x ** 2 for x in nums]                     # List comprehension
print(squares)                                        # prints [0, 1, 4, 9, 16]

even_squares = [x ** 2 for x in nums if x % 2 == 0] # Add additional conditions
print(even_squares)                                   # prints "[0, 4, 16]"

# List comprehension can be a slick way to create lists


In [ ]:
# Dictionaries
# A dictionary stores (key,value) pairs

# Create a new dictionary
example_dict = {'cat': 'cute', 'dog': 'furry'}

# Get entries
print('cat' in example_dict)     # Check if a dictionary has a given key; prints "True"
print(example_dict['cat'])       # Get an entry from a dictionary; prints "cute"
example_dict['fish'] = 'wet';print(example_dict['fish'])     # Set an entry in a dictionary; prints "wet"
# print(example_dict['monkey'])  # KeyError: 'monkey' not a key of d
print(example_dict.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(example_dict.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
del example_dict['fish']         # Remove an element from a dictionary
print(example_dict.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

# Loops
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"
d = {'person': 2, 'cat': 4, 'spider': 8}

#Solution_1:
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))
#Solution_2:   
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))


# Dict comprehensions
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)  # Prints "{0: 0, 2: 4, 4: 16}"

In [ ]:
# Sets
# A set contains unordered distinct items

animals = {'cat', 'dog'}
print('cat' in animals)                        # Check if an element is in a set; prints "True"
animals.add('fish')                            # Add an element to a set
print(len(animals))                            # Number of elements in a set; prints "3"
animals.add('cat'); print(len(animals))        # Adding an element that is already in the set does nothing; prints "3"
animals.remove('cat');print(len(animals))      # Remove an element from a set; prints "2"

#NO SET INDEXING

# Loops
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))       # Prints "#1: fish", "#2: dog", "#3: cat"

### Summary
1. None of above types have a fixed type: all can contain anything
2. Tuples is in many ways similar to a list; it contains immutable ordered list of values. 
   One key difference is that tuples can be used as keys in dictionaries and as elements of sets while lists cannot.


## 2.3 Functions

In [ ]:
# In python, we define functions using keyword def

def example_func(a, b = 10 , loud = False):
    if loud:                                          # Boolean statements
        print('%s is %d years younger than me.' % (a.upper(), b))
    else:
        print('%s is %d years younger than me.' % (a, b))

def main():
    name = 'Alice'
    age = 5
    example_func(a = name)
    example_func(a = name, b = age, loud = True)
    
    
if __name__=='__main__':
    main()
    

# In the above function, we pass a default value for b, and take loud as optional keyword arguments. 
# You can call it from command line and see what's the difference

## 2.4 Classes

In [ ]:
class Vehicle:
    
    # Constructor, initialize the class to get an instance using some parameters
    def __init__(self, make, name, price = 100):
        self.name = name                                   # instance variables                                 
        self.make = make                                                    
        self.price = price                                 
        self.odometer = 0
    
    # Do some something with the instance
    def drive(self, distance):
        self.odometer += distance
    
    def compute_price(self):
        try:
            price = self.price / self.odometer
        except ZeroDivisionError:
            price = self.price
        return price
    
# Use of a class
v = Vehicle('Honda', 'Accord', price = 20000)     # Instantiate the class, get an instance
print(v.compute_price())                          # Call an instance method

# Use of a class
if __name__ == '__main__':
    family_car = Vehicle('Honda', 'Accord', price = 20000)
    family_car.drive(100)
    print(family_car.compute_price())


# 3 Numpy & Scipy

## 3.1 Arrays

In [ ]:
import numpy as np
# All entries are of the same type

# Generate Ndarrays
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.dtype)            # Get the datatype of the ndarry; prints "int64", it can be explicitly specified when constructing the array
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"


a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.rand(2,2)  # Create an array filled with random values

f = np.array([[0,1,2],[3,4,5],[6,7,8]]) # Create an array from a python list

In [ ]:
# Slicing

# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2; b is the following array of shape (2, 2):
b = a[:2, 1:3] # prints   [[2 3]
               #           [6 7]]

# A slice of an array is a view into the same data, so modifying it will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank
row_r1 = a[1, :]    # Rank 1 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
# Slices yields an array of the same rank as the original array
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# The same distinction also when accessing columns of an array

In [ ]:
# Integer array indexing
# When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. 
# In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array.

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"; shape(3,)
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Equivalent to above example; prints "[1 4 5]"

# When using integer array indexing, you can reuse the same element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"
print(np.array([a[0, 1], a[0, 1]]))  # Equivalant to above example; prints "[2 2]"


# Boolean array indexing
bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
# Returns a numpy array of Booleans of the same shape as a, where each slot of bool_idx tellswhether that element of a is > 2
print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"
# Use boolean array indexing to construct a rank 1 array consisting of the elements of a corresponding to the True values of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"
# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

## 3.2 Arithmetic  Operations on Ndarrays

In [ ]:
import numpy as np
# Arithmetic operations

# Same shape

# Element-wise Sum
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))
# both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]

# Element-wise multiplication(*)
print(x * y)
print(np.multiply(x, y))
# both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]

# Dot product
# 1. between vector and vector
x = np.array([1,2,3,4])
y = np.array([5,10,15,20])
print(np.dot(x,y))
print(sum([i*j for (i, j) in zip(x, y)]))
# both produce "150"

# 2. between vector and matrix
x = np.array([[1,10],[2,5],[3,3]])
y = np.array([3,4])
print(np.dot(x, y))
# both produce the array "[43,26,21]"

# 3. between matrix and matrix: matrix multiplication
x = np.array([[1,5],[2,3],[3,10]])
y = np.array([[3,4],[4,5]])
print(np.dot(x, y))
print(np.matmul(x, y))
# both produce the array
# [[23,29],
#  [18,23],
#  [49,62]]

# According to official document,it is recommend to use np.matmul()

In [ ]:
# Sum: compute sum of all elements, requires the dtype to be scalar
x = np.array([[1,2],
              [3,4]], dtype = np.int64)
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"
# Apply along the dimension gets rid of that dimension and replaces it with the function applied across that dimension

# Transpose
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"
# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

# Reshape
x.shape          # Prints "(2,2)"
x.reshape(4,)    # Prints the array "[1,2,3,4]"
x.reshape(4,-1)  # Prints the array "[[1],[2],[3],[4]]"
x.reshape(1, 4)  # Prints the array "[[1,2,3,4]]"

## 3.3 Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [ ]:
# Allows to work with arrays of different shapes when performing arithmetic operations

# Example 1: add a vector to each row of the matrix
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x


# Solution 1: Explicitly loop
for i in range(4):
    y[i, :] = x[i, :] + v  
    # however when the matrix x is very large, computing an explicit loop in Python could be slow. 
# Solution 2: Stack 4 copies of v on top of each other
vv = np.tile(v, (4, 1))
print(vv)                 # Prints "[[1 0 1],[1 0 1],[1 0 1],[1 0 1]]"
y = x + vv                # Add x and vv elementwise
# Solution 3: Broadcasting
y = x + v 
# Prints "[[ 2  2  4]
#          [ 5  5  7]
#          [ 8  8 10]
#          [11 11 13]]"

### General rules of broadcasting

1. Write out the shapes of each ndarray
2. Starting from the back, that dimension has compatible values if either:
    a. They are the same value, or 
    b. One of them is a 1
3. The size of the resulting array is the maxinum along each dimension
4. If either argument is N-D, N > 2, it is treated as a stack of matrices residing in the last two indexes and broadcast accordingly(See example 5)

In [ ]:
# Broadcasting case

# Example 2: Add a scalar to an ndarray
x = np.array([1,10,15,100])
y = 10
print(x + y)        # prints the array "[11, 20, 25, 110]"

# Example 3: Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
print(np.reshape(v, (3, 1)) * w)
# First reshape v to be a column vector of shape (3, 1), then broadcast it against w to yield an output of shape (3, 2)
# [[ 4  5]
#  [ 8 10]
#  [12 15]]

# Example 4: Add a vector to each column of a matrix
x = np.array([[1,2,3], [4,5,6]])    # x has shape (2, 3)
v = np.array([1,2,3])               # w has shape (2,)
# Transpose x then it has shape (3, 2) and can be broadcast against w to yield a result of shape (3, 2)
# Transposing this result yields the final result of shape (2, 3)
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1); then broadcast it directly against x
print(x + np.reshape(w, (2, 1)))
# [[ 5  6  7]
#  [ 9 10 11]]


# Example 5: 
a = np.random.random((3,4,5,6))
b = np.random.random((4,6,7))
c = np.matmul(a,b)
print(c.shape)              # Prints "(3,4,5,7)"
# Hint: The last two dimensions represent matrices, so we take those out and broadcast the rest: (3, 4) and (4,)
#       Using our broadcasting rules, the result of broadcastingthese shapes will be (3, 4)
#       Matrix multiplication results in a matrix of shape (5, 7)
#       Our output will have shape (3, 4, 5, 7)

d = np.dot(a, b)
print(d.shape)             # Prints "(3,4,5,4,7)"

### Advices

1. If you are unsure how an operation will work on ndarrays of a certain shape, try it out
2. Create random matrices that have the shape you are looking at, do the operation, and check the shape of the output
3. Python scripting in the terminal is great for this

# 4 Matplotlib

## 4.1 Plotting

In [ ]:
%matplotlib inline  

import matplotlib
import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinate for points on a sine curve
x = np.arange(0, 3*np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()                       # You must call plt.show() to make graphics appear.

## 4.2 Subplot

In [ ]:
%matplotlib inline  

import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()


# Demo

Calculate the eigenvector associated with the dominant eigenvalue.

Use the power iteration method: $b_{k+1}= \frac{Ab_k}{||Ab_k||} $


In [ ]:
import numpy as np

def power_iteration(A, tolerance=1e-7):
    b_old = np.random.rand(A.shape[1])
    b = np.random.rand(A.shape[1])
    num_iterations = 0
    while num_iterations == 0 or np.linalg.norm(b_old - b) > tolerance:
        b_old = np.copy(b)
        b = np.dot(A, b)
        b_norm = np.linalg.norm(b)
        b /= b_norm
        num_iterations += 1
    return np.dot(A, b), b, num_iterations

def main():
    A = np.array([[.5, .4], [.2, .8]])
    ab, b, number_iterations = power_iteration(A)

    eig1 = ab[0] / b[0]
    eig2 = ab[1] / b[1]
    assert(np.abs((eig1 - eig2) / eig2) < 1e-5)

    b /= b[1]

    print(eig1, b, number_iterations)

if __name__ == '__main__':
    main()

Reference:

[1] Stanford CS231N python tutorial: https://cs231n.github.io/python-numpy-tutorial

[2] Stanford CS224N python review: http://web.stanford.edu/class/cs224n/